-- Add curated Jira-style relation types (each with its inverse).
ALTER TYPE "TicketRelationType" ADD VALUE IF NOT EXISTS 'CLONES';
ALTER TYPE "TicketRelationType" ADD VALUE IF NOT EXISTS 'CLONED_BY';
ALTER TYPE "TicketRelationType" ADD VALUE IF NOT EXISTS 'DUPLICATES';
ALTER TYPE "TicketRelationType" ADD VALUE IF NOT EXISTS 'DUPLICATED_BY';
ALTER TYPE "TicketRelationType" ADD VALUE IF NOT EXISTS 'CAUSES';
ALTER TYPE "TicketRelationType" ADD VALUE IF NOT EXISTS 'CAUSED_BY';
ALTER TYPE "TicketRelationType" ADD VALUE IF NOT EXISTS 'TESTS';
ALTER TYPE "TicketRelationType" ADD VALUE IF NOT EXISTS 'TESTED_BY';
ALTER TYPE "TicketRelationType" ADD VALUE IF NOT EXISTS 'SPLIT_FROM';
ALTER TYPE "TicketRelationType" ADD VALUE IF NOT EXISTS 'SPLIT_TO';
